import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Header from '../componants/Header'
import Genre from '../componants/Genre'

export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>RetroJ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Genre />


    </div>
  )
}
